/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import modelo.User;

/**
 *
 * @author Leslie Diaz
 */
public class Modificacion extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    Validar validar = new Validar();
    String passEncrip;
    Color color = new Color(180, 076, 067);
    User salida = new User();
    UserBD ubd = new UserBD(conexion);
    User auxu = new User();

    public Modificacion(User u) throws ParseException {
        initComponents();
        setLocationRelativeTo(null);
        Date aux = new Date();
        datefechana.setMaxSelectableDate(aux);
        datefechana.getDateEditor().setEnabled(false);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        aux = sdf.parse(u.getFechanacimiento());
        datefechana.getDateEditor().setDate(aux);
        txtapepat.setText(u.getApellido());
        txtnombres.setText(u.getNombre());
        formatemail.setText(u.getCorreo());
        formatemail.setEnabled(false);
        txtubicacion.setText(u.getUbicacion());
        auxu = u;
        validacionPegar();
    }

    public void validacionPegar() {
        InputMap map1 = txtapepat.getInputMap(txtapepat.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map3 = txtnombres.getInputMap(txtnombres.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map7 = formatemail.getInputMap(formatemail.WHEN_FOCUSED);
        map7.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map8 = txtpass.getInputMap(txtpass.WHEN_FOCUSED);
        map8.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map9 = txtubicacion.getInputMap(txtubicacion.WHEN_FOCUSED);
        map9.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtapepat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datefechana = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        formatemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtubicacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 102)), "Modificar Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 18))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Apellido:");
        jPanel1.add(jLabel1);

        txtapepat.setToolTipText("Solo Utilize Letras");
        txtapepat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtapepatFocusGained(evt);
            }
        });
        txtapepat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapepatKeyTyped(evt);
            }
        });
        jPanel1.add(txtapepat);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3);

        txtnombres.setToolTipText("Solo Utilize Letras");
        txtnombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombresFocusGained(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombres);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel5);

        datefechana.setToolTipText("");
        datefechana.setDateFormatString("dd-MM-yyyy");
        datefechana.setFocusable(false);
        jPanel1.add(datefechana);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Correo Electrónico:");
        jPanel1.add(jLabel6);

        formatemail.setToolTipText("ejemplo@email.com");
        formatemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatemailFocusGained(evt);
            }
        });
        formatemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formatemailKeyTyped(evt);
            }
        });
        jPanel1.add(formatemail);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Ubicacion: ");
        jPanel1.add(jLabel2);
        jPanel1.add(txtubicacion);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Ingrese la Contraseña:");
        jPanel1.add(jLabel7);

        txtpass.setToolTipText("minimo 8 caracteres");
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        jPanel1.add(txtpass);

        jPanel5.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 34, 0));

        btnmodificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visto.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnmodificar);

        btncancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar);

        jPanel5.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel5, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        conexion = new Conexion();
        ubd.setConexion(conexion);
        int aux = 0;

        String apepat = txtapepat.getText();
        String nombre = txtnombres.getText();
        String email = formatemail.getText();
        String pass = txtpass.getText();
        String fechanacimiento = "";
        String ubicacion= txtubicacion.getText();
        try {
            Date fecha = datefechana.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            fechanacimiento = sdf.format(fecha);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.INFORMATION_MESSAGE);
//            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }

        ArrayList<String> campos = new ArrayList<>();
        campos.add(apepat);
        campos.add(nombre);
        campos.add(email);
        campos.add(pass);
        campos.add(fechanacimiento);
        campos.add(ubicacion);

        List<Integer> camposVacios = validar.camposVacios(campos);
        if (!camposVacios.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar los Campos Vacios o Incorrectos");
            for (Integer camposVacio : camposVacios) {
                if (null != camposVacio) {
                    switch (camposVacio) {
                        case 0:
                            txtapepat.setBackground(color);
                            break;
                        case 1:
                           txtnombres.setBackground(color);
                            break;
                        case 2:
                            formatemail.setBackground(color);
                            break;
                        case 3:
                            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
                            break;
                        case 5:
                            txtubicacion.setBackground(color);
                            break;   
                        default:
                            break;
                    }
                }
            }
        } else {
            passEncrip = validar.encriptaEnMD5(pass);
            passEncrip = validar.encriptaEnMD5(passEncrip);

            boolean estado = validar.isEmail(email);
            if (estado == true) {
                formatemail.setBackground(Color.white);
            } else {
                mensaje();
                formatemail.setBackground(color);
            }

           salida.setApellido(apepat);
           salida.setNombre(nombre);
           salida.setFechanacimiento(fechanacimiento);
           salida.setContrasenia(passEncrip);
           salida.setCorreo(auxu.getCorreo());
           salida.setUbicacion(ubicacion);
           salida.setListacarrito(auxu.getListacarrito());
           if (auxu.getContrasenia().equals(passEncrip)) {
                    aux = ubd.cambiarUsuario(salida);
                    if (aux == -1) {
                        JOptionPane.showMessageDialog(null, "Error en el cambio");
                    } else {
                        JOptionPane.showMessageDialog(null, "Cambio Exitoso");
                        new Principal(salida).setVisible(true);
                        dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
                }

            
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        new Principal(auxu).setVisible(true);
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    public void mensaje() {
        JOptionPane.showMessageDialog(null, "Campo /os incorrecto /os", "Validacion de Campos", JOptionPane.INFORMATION_MESSAGE);
    }

    private void txtapepatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapepatKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != 'ñ') && (car != 'é') && (car != 'á') && (car != 'í') && (car != 'ó') && (car != 'ú') && (car != 'Ñ') && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtapepatKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != 'ñ') && (car != 'é') && (car != 'á') && (car != 'í') && (car != 'ó') && (car != 'ú') && (car != 'Ñ') && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void formatemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatemailKeyTyped
        char car = evt.getKeyChar();
        if (car == ';') {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_formatemailKeyTyped

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        txtpass.setBackground(Color.white);
    }//GEN-LAST:event_txtpassFocusGained

    private void formatemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatemailFocusGained
        formatemail.setBackground(Color.white);
    }//GEN-LAST:event_formatemailFocusGained

    private void txtnombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombresFocusGained
        txtnombres.setBackground(Color.white);
    }//GEN-LAST:event_txtnombresFocusGained

    private void txtapepatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapepatFocusGained
        txtapepat.setBackground(Color.white);
    }//GEN-LAST:event_txtapepatFocusGained

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser datefechana;
    private javax.swing.JTextField formatemail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtapepat;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtubicacion;
    // End of variables declaration//GEN-END:variables
}
