/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AuxiliarArticulo;
import controlador.Conexion;
import controlador.HiloBasedeDatos;
import controlador.HiloBusqueda;
import controlador.ArticuloBD;
import controlador.UserBD;

import java.awt.Event;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import modelo.User;


/**
 *
 * @author Leslie Diaz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    User aux;
    Conexion cnx = new Conexion();
    ArticuloBD pbd = new ArticuloBD(cnx);
    UserBD ubd = new UserBD(cnx);
    AuxiliarArticulo ap = new AuxiliarArticulo();
    ArrayList<AuxiliarArticulo> listacarrito = new ArrayList<>();

    public Principal(User u) {
        initComponents();
        this.setSize(600, 500);
        setLocationRelativeTo(null);
        if (u.getNombre().equals("")) {
            lblnombre.setText("Invitado");
            mianiadir.setEnabled(false);
            mieliminar.setEnabled(false);
            miperfil.setEnabled(false);
            mimodificaru.setEnabled(false);
            micerrarsesion.setEnabled(false);
            micarrito.setEnabled(false);
        } else {
            lblnombre.setText(u.getNombre() + " " + u.getApellido());
            btningresar.setEnabled(false);
            btnregistrarse.setEnabled(false);
        }
        aux = u;
        if (pbd.articulos(u) != 2) {
            mieliminar.setEnabled(false);
        }
        validacionPegar();
        HiloBasedeDatos hilo = new HiloBasedeDatos(jProgressBar1, lcasas, pbd);
        hilo.setDaemon(true);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbcampo = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblbienvenido = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        lblnombre = new javax.swing.JLabel();
        btnregistrarse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lcasas = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        baniadir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mianiadir = new javax.swing.JMenuItem();
        mieliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miperfil = new javax.swing.JMenuItem();
        mimodificaru = new javax.swing.JMenuItem();
        micarrito = new javax.swing.JMenuItem();
        micerrarsesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Busqueda por:");
        jPanel9.add(jLabel3);

        cbcampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbcampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Categoria" }));
        jPanel9.add(cbcampo);

        jPanel7.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        txtbuscar.setText("Buscar");
        txtbuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtbuscarCaretUpdate(evt);
            }
        });
        txtbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbuscarFocusLost(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });
        jPanel10.add(txtbuscar);

        jPanel7.add(jPanel10);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));
        jPanel5.add(jPanel8);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        lblbienvenido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblbienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbienvenido.setText("Bienvenido");
        jPanel6.add(lblbienvenido);

        btningresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        jPanel6.add(btningresar);

        lblnombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombre.setText("\"Invitado\"");
        jPanel6.add(lblnombre);

        btnregistrarse.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnregistrarse.setText("Registrarse");
        btnregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarseActionPerformed(evt);
            }
        });
        jPanel6.add(btnregistrarse);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lcasas.setVisibleRowCount(4);
        lcasas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcasasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lcasas);

        jPanel3.add(jScrollPane1);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        baniadir.setText("Añadir Al Carrito");
        baniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baniadirActionPerformed(evt);
            }
        });
        jPanel11.add(baniadir);

        jPanel3.add(jPanel11);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jProgressBar1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jProgressBar1.setString("Cargando ...");
        jProgressBar1.setStringPainted(true);
        jPanel4.add(jProgressBar1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, "card2");

        jMenu1.setText("Propiedades");

        mianiadir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mianiadir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        mianiadir.setText("Añadir");
        mianiadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mianiadirActionPerformed(evt);
            }
        });
        jMenu1.add(mianiadir);

        mieliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mieliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        mieliminar.setText("Eliminar");
        mieliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mieliminarActionPerformed(evt);
            }
        });
        jMenu1.add(mieliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario");

        miperfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miperfil.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        miperfil.setText("Perfil de Usuario");
        miperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miperfilActionPerformed(evt);
            }
        });
        jMenu2.add(miperfil);

        mimodificaru.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mimodificaru.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        mimodificaru.setText("Modificar");
        mimodificaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimodificaruActionPerformed(evt);
            }
        });
        jMenu2.add(mimodificaru);

        micarrito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        micarrito.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        micarrito.setText("Carrito");
        micarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micarritoActionPerformed(evt);
            }
        });
        jMenu2.add(micarrito);

        micerrarsesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        micerrarsesion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        micerrarsesion.setText("Cerrar Sesion");
        micerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micerrarsesionActionPerformed(evt);
            }
        });
        jMenu2.add(micerrarsesion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void validacionPegar() {
        InputMap map1 = txtbuscar.getInputMap(txtbuscar.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }

    private void mieliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mieliminarActionPerformed
        EliminarArticulo ec = new EliminarArticulo(aux);
        ec.setVisible(true);
        dispose();
    }//GEN-LAST:event_mieliminarActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        new Ingreso().setVisible(true);
        dispose();
    }//GEN-LAST:event_btningresarActionPerformed

    private void btnregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarseActionPerformed
        new Registro().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregistrarseActionPerformed

    private void mianiadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mianiadirActionPerformed
        AgregarArticulo ac = new AgregarArticulo(aux);
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_mianiadirActionPerformed

    private void micerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micerrarsesionActionPerformed
        Ingreso i = new Ingreso();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_micerrarsesionActionPerformed

    private void mimodificaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimodificaruActionPerformed
        try {
            new Modificacion(aux).setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_mimodificaruActionPerformed

    private void lcasasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcasasMouseClicked
        try{
            ap = (AuxiliarArticulo)lcasas.getSelectedValue();
            User u = ubd.obtenerUsuario(ap.getIdPersona());
            new MostarArticulo(ap,u).setVisible(true);
        }catch(NullPointerException ex){
            
        }
        
       
    }//GEN-LAST:event_lcasasMouseClicked

    private void miperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miperfilActionPerformed
        new PerfilUsuario(aux, "").setVisible(true);
    }//GEN-LAST:event_miperfilActionPerformed

    private void txtbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusGained
        txtbuscar.setText("");
    }//GEN-LAST:event_txtbuscarFocusGained

    private void txtbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusLost
        if (txtbuscar.getText().trim().equals("")) {
            txtbuscar.setText("Buscar");
        }
    }//GEN-LAST:event_txtbuscarFocusLost

    private void txtbuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtbuscarCaretUpdate
        HiloBusqueda hilo = new HiloBusqueda(lcasas);
        hilo.setCampo((String) cbcampo.getSelectedItem());
        hilo.setBusqueda(txtbuscar.getText());
        hilo.setDaemon(true);
        hilo.start();
    }//GEN-LAST:event_txtbuscarCaretUpdate

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != 'ñ') && (car != 'á') && (car != 'í') && (car != 'ó') && (car != 'ú') && (car != 'Ñ') && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void micarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micarritoActionPerformed
        Carrito car = new Carrito(aux);
        car.setVisible(true);
    }//GEN-LAST:event_micarritoActionPerformed

    private void baniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baniadirActionPerformed
        AuxiliarArticulo aacarrito;
        try{
           aacarrito = (AuxiliarArticulo)lcasas.getSelectedValue();
        }catch(NullPointerException e){
            aacarrito= new AuxiliarArticulo();
        }
        if(listacarrito.isEmpty()){
            listacarrito.add(aacarrito);
            JOptionPane.showMessageDialog(null, "Articulo añadido con exito!");
        }else{
            for (int i = 0; i < listacarrito.size(); i++) {
                AuxiliarArticulo aa = listacarrito.get(i);
                if(aacarrito.equals(aa)){
                    JOptionPane.showMessageDialog(null,"Articulo ya existe en el carrito");
                }else{
                    listacarrito.add(aacarrito);
                    JOptionPane.showMessageDialog(null, "Articulo añadido con exito!");
                }
                break;
            }
        }
       aux.setListacarrito(listacarrito);
    }//GEN-LAST:event_baniadirActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baniadir;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnregistrarse;
    private javax.swing.JComboBox<String> cbcampo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbienvenido;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JList<AuxiliarArticulo> lcasas;
    private javax.swing.JMenuItem mianiadir;
    private javax.swing.JMenuItem micarrito;
    private javax.swing.JMenuItem micerrarsesion;
    private javax.swing.JMenuItem mieliminar;
    private javax.swing.JMenuItem mimodificaru;
    private javax.swing.JMenuItem miperfil;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
