/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AccionesBoing;
import controlador.LeerEscribirArchivos;
import controlador.Validar;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import modelo.BarcoVela;
import modelo.Boing747;
import modelo.HondaXR25;
import modelo.HondaXR600;

/**
 *
 * @author PAVILLION
 */
public class Control extends javax.swing.JFrame {

    int numviajes = 0;
    Boing747 boing = new Boing747(numviajes, 893.00, 945);
    BarcoVela vela = new BarcoVela(300.00, 400);
    HondaXR25 honda1 = new HondaXR25(40,70);
    HondaXR600 honda2 = new HondaXR600(50,90);
    AccionesBoing accionesb = new AccionesBoing();
    Validar validar = new Validar();
    LeerEscribirArchivos leer = new LeerEscribirArchivos();

    /**
     * Creates new form Control
     */
    public Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bboing = new javax.swing.JToggleButton();
        bhonda600 = new javax.swing.JToggleButton();
        bhonda25 = new javax.swing.JToggleButton();
        bfalcon = new javax.swing.JToggleButton();
        bbarco = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bencendido = new javax.swing.JToggleButton();
        bapagado = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        bdesplazarseford = new javax.swing.JButton();
        baumentarvelocford = new javax.swing.JButton();
        bdisminuirvelocford = new javax.swing.JButton();
        bfrenarford = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        baumentarboing = new javax.swing.JButton();
        bdespegarboing = new javax.swing.JButton();
        baterrizarboing = new javax.swing.JButton();
        bdisminuirboing = new javax.swing.JButton();
        bfrenarboing = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        bizarvela = new javax.swing.JButton();
        baumentavela = new javax.swing.JButton();
        bdisminuirvela = new javax.swing.JButton();
        bdetenervela = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bmostrarbitacora = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de Control", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        grupo.add(bboing);
        bboing.setText("Boing747");
        bboing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bboingActionPerformed(evt);
            }
        });
        jPanel2.add(bboing);

        grupo.add(bhonda600);
        bhonda600.setText("HondaXR600");
        bhonda600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhonda600ActionPerformed(evt);
            }
        });
        jPanel2.add(bhonda600);

        grupo.add(bhonda25);
        bhonda25.setText("HondaXR25");
        bhonda25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhonda25ActionPerformed(evt);
            }
        });
        jPanel2.add(bhonda25);

        grupo.add(bfalcon);
        bfalcon.setText("FordFalcon");
        bfalcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfalconActionPerformed(evt);
            }
        });
        jPanel2.add(bfalcon);

        grupo.add(bbarco);
        bbarco.setText("BarcoVela");
        bbarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbarcoActionPerformed(evt);
            }
        });
        jPanel2.add(bbarco);

        jPanel6.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup2.add(bencendido);
        bencendido.setText("Encendido");
        bencendido.setEnabled(false);
        bencendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bencendidoActionPerformed(evt);
            }
        });
        jPanel8.add(bencendido);

        buttonGroup2.add(bapagado);
        bapagado.setSelected(true);
        bapagado.setText("Apagado");
        bapagado.setEnabled(false);
        bapagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bapagadoActionPerformed(evt);
            }
        });
        jPanel8.add(bapagado);

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setLayout(new java.awt.GridLayout(1, 3));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "FordFalcon | Honda XR600-XR25", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel12.setLayout(new java.awt.GridLayout(2, 2));

        bdesplazarseford.setText("Desplazarse");
        bdesplazarseford.setEnabled(false);
        jPanel12.add(bdesplazarseford);

        baumentarvelocford.setText("AumentarVelocidad");
        baumentarvelocford.setEnabled(false);
        jPanel12.add(baumentarvelocford);

        bdisminuirvelocford.setText("Disminuir Velocidad");
        bdisminuirvelocford.setEnabled(false);
        jPanel12.add(bdisminuirvelocford);

        bfrenarford.setText("Frenar");
        bfrenarford.setEnabled(false);
        bfrenarford.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfrenarfordActionPerformed(evt);
            }
        });
        jPanel12.add(bfrenarford);

        jPanel10.add(jPanel12);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Boing747", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel15.setLayout(new java.awt.GridLayout(2, 2));

        baumentarboing.setText("Aumentar Velocidad");
        baumentarboing.setEnabled(false);
        baumentarboing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baumentarboingActionPerformed(evt);
            }
        });
        jPanel15.add(baumentarboing);

        bdespegarboing.setText("Despegar");
        bdespegarboing.setEnabled(false);
        bdespegarboing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdespegarboingActionPerformed(evt);
            }
        });
        jPanel15.add(bdespegarboing);

        baterrizarboing.setText("Aterrizar");
        baterrizarboing.setEnabled(false);
        baterrizarboing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baterrizarboingActionPerformed(evt);
            }
        });
        jPanel15.add(baterrizarboing);

        bdisminuirboing.setText("Disminuir Velocidad");
        bdisminuirboing.setEnabled(false);
        bdisminuirboing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdisminuirboingActionPerformed(evt);
            }
        });
        jPanel15.add(bdisminuirboing);

        bfrenarboing.setText("Frenar");
        bfrenarboing.setEnabled(false);
        bfrenarboing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfrenarboingActionPerformed(evt);
            }
        });
        jPanel15.add(bfrenarboing);

        jPanel11.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BarcoVela", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel16.setLayout(new java.awt.GridLayout(2, 2));

        bizarvela.setText("Izar Vela");
        bizarvela.setEnabled(false);
        jPanel16.add(bizarvela);

        baumentavela.setText("Aumentar Velocidad");
        baumentavela.setEnabled(false);
        baumentavela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baumentavelaActionPerformed(evt);
            }
        });
        jPanel16.add(baumentavela);

        bdisminuirvela.setText("Disminuir Velocidad");
        bdisminuirvela.setEnabled(false);
        jPanel16.add(bdisminuirvela);

        bdetenervela.setText("Frenar");
        bdetenervela.setEnabled(false);
        jPanel16.add(bdetenervela);

        jPanel11.add(jPanel16);

        jPanel9.add(jPanel11);

        jPanel4.add(jPanel9);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setViewportView(jList1);

        jPanel5.add(jScrollPane1);

        bmostrarbitacora.setText("Mostrar Bitacora");
        bmostrarbitacora.setEnabled(false);
        bmostrarbitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmostrarbitacoraActionPerformed(evt);
            }
        });
        jPanel5.add(bmostrarbitacora);

        jPanel3.add(jPanel5);

        jPanel6.add(jPanel3);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));
        jPanel7.add(jProgressBar1);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhonda25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhonda25ActionPerformed
        bencendido.setEnabled(true);
        bboing.setEnabled(false);
        bhonda25.setEnabled(false);
        
    }//GEN-LAST:event_bhonda25ActionPerformed

    private void bapagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bapagadoActionPerformed
        bencendido.setEnabled(false);
        bapagado.setEnabled(false);
        bboing.setEnabled(true);
        bbarco.setEnabled(true);
        bfalcon.setEnabled(true);
        bhonda25.setEnabled(true);
        bhonda600.setEnabled(true);
        if (bboing.isSelected() || bbarco.isSelected() || bhonda25.isSelected() || bhonda600.isSelected() || bfalcon.isSelected()) {
            baterrizarboing.setEnabled(false);
            baumentarboing.setEnabled(false);
            bfrenarboing.setEnabled(false);
            bmostrarbitacora.setEnabled(false);
            bdisminuirboing.setEnabled(false);
            bdespegarboing.setEnabled(false);
            baumentarvelocford.setEnabled(false);
            baumentavela.setEnabled(false);
            bdesplazarseford.setEnabled(false);
            bdisminuirvela.setEnabled(false);
            bdisminuirvelocford.setEnabled(false);
            bfrenarford.setEnabled(false);
            bizarvela.setEnabled(false);
            bdetenervela.setEnabled(false);
        }
        grupo.clearSelection();
    }//GEN-LAST:event_bapagadoActionPerformed

    private void bfrenarfordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfrenarfordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bfrenarfordActionPerformed

    private void baumentavelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baumentavelaActionPerformed

    }//GEN-LAST:event_baumentavelaActionPerformed

    private void bboingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bboingActionPerformed
        bencendido.setEnabled(true);
        bboing.setEnabled(false);
        bbarco.setEnabled(true);
        bfalcon.setEnabled(true);
        bhonda25.setEnabled(true);
        bhonda600.setEnabled(true);
    }//GEN-LAST:event_bboingActionPerformed

    private void bencendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bencendidoActionPerformed
        bapagado.setEnabled(true);
        bencendido.setEnabled(false);
        if (bboing.isSelected()) {
            
            baterrizarboing.setEnabled(true);
            baumentarboing.setEnabled(true);
            bfrenarboing.setEnabled(true);
            bmostrarbitacora.setEnabled(true);
            bdisminuirboing.setEnabled(true);
            bdespegarboing.setEnabled(true);
            baumentarvelocford.setEnabled(false);
            baumentavela.setEnabled(false);
            bdesplazarseford.setEnabled(false);
            bdisminuirvela.setEnabled(false);
            bdisminuirvelocford.setEnabled(false);
            bfrenarford.setEnabled(false);
            bizarvela.setEnabled(false);
            bdetenervela.setEnabled(false);
            boing.setViajes(boing.getViajes() + 1);
            accionesb.acciones(boing);
        } else if (bbarco.isSelected()) {
            baterrizarboing.setEnabled(false);
            baumentarboing.setEnabled(false);
            bfrenarboing.setEnabled(false);
            bmostrarbitacora.setEnabled(true);
            bdisminuirboing.setEnabled(false);
            bdespegarboing.setEnabled(false);
            baumentarvelocford.setEnabled(false);
            baumentavela.setEnabled(true);
            bdesplazarseford.setEnabled(false);
            bdisminuirvela.setEnabled(true);
            bdisminuirvelocford.setEnabled(false);
            bfrenarford.setEnabled(false);
            bizarvela.setEnabled(true);
            bdetenervela.setEnabled(true);
        } else if (bhonda25.isSelected() || bhonda600.isSelected() || bfalcon.isSelected()) {
            baterrizarboing.setEnabled(false);
            baumentarboing.setEnabled(false);
            bfrenarboing.setEnabled(false);
            bmostrarbitacora.setEnabled(true);
            bdisminuirboing.setEnabled(false);
            bdespegarboing.setEnabled(false);
            baumentarvelocford.setEnabled(true);
            baumentavela.setEnabled(false);
            bdesplazarseford.setEnabled(true);
            bdisminuirvela.setEnabled(false);
            bdisminuirvelocford.setEnabled(true);
            bfrenarford.setEnabled(true);
            bizarvela.setEnabled(false);
            bdetenervela.setEnabled(false);
        }


    }//GEN-LAST:event_bencendidoActionPerformed

    private void bhonda600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhonda600ActionPerformed
        bencendido.setEnabled(true);
        bboing.setEnabled(true);
        bbarco.setEnabled(true);
        bfalcon.setEnabled(true);
        bhonda25.setEnabled(true);
        bhonda600.setEnabled(false);
    }//GEN-LAST:event_bhonda600ActionPerformed

    private void bfalconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfalconActionPerformed
        bencendido.setEnabled(true);
        bboing.setEnabled(true);

        bbarco.setEnabled(true);
        bfalcon.setEnabled(false);
        bhonda25.setEnabled(true);
        bhonda600.setEnabled(true);
    }//GEN-LAST:event_bfalconActionPerformed

    private void bbarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbarcoActionPerformed
        bencendido.setEnabled(true);
        bboing.setEnabled(true);

        bbarco.setEnabled(false);
        bfalcon.setEnabled(true);
        bhonda25.setEnabled(true);
        bhonda600.setEnabled(true);
    }//GEN-LAST:event_bbarcoActionPerformed

    private void baumentarboingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baumentarboingActionPerformed
    String aumentar = "Velocidad Aumenta";
    accionesb.accionesBoing(aumentar); 
    }//GEN-LAST:event_baumentarboingActionPerformed

    private void bdespegarboingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdespegarboingActionPerformed
    String despega = "Boing Despega";
    accionesb.accionesBoing(despega); 
    }//GEN-LAST:event_bdespegarboingActionPerformed

    private void baterrizarboingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baterrizarboingActionPerformed
    String aterriza = "Boing Aterriza";
    accionesb.accionesBoing(aterriza); 
    }//GEN-LAST:event_baterrizarboingActionPerformed

    private void bdisminuirboingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdisminuirboingActionPerformed
    String disminuir = "Velocidad Disminuye";
    accionesb.accionesBoing(disminuir); 
    }//GEN-LAST:event_bdisminuirboingActionPerformed

    private void bfrenarboingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfrenarboingActionPerformed
    String freno = "Frenando";
    accionesb.accionesBoing(freno); 
    }//GEN-LAST:event_bfrenarboingActionPerformed

    private void bmostrarbitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmostrarbitacoraActionPerformed
       if(bboing.isSelected()){
           ArrayList <String> listaboing = (ArrayList) leer.leerArchivo("listaAccionesBoing");
           validar.actualizarListas(listaboing, jList1);
       }
    }//GEN-LAST:event_bmostrarbitacoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bapagado;
    private javax.swing.JButton baterrizarboing;
    private javax.swing.JButton baumentarboing;
    private javax.swing.JButton baumentarvelocford;
    private javax.swing.JButton baumentavela;
    private javax.swing.JToggleButton bbarco;
    private javax.swing.JToggleButton bboing;
    private javax.swing.JButton bdespegarboing;
    private javax.swing.JButton bdesplazarseford;
    private javax.swing.JButton bdetenervela;
    private javax.swing.JButton bdisminuirboing;
    private javax.swing.JButton bdisminuirvela;
    private javax.swing.JButton bdisminuirvelocford;
    private javax.swing.JToggleButton bencendido;
    private javax.swing.JToggleButton bfalcon;
    private javax.swing.JButton bfrenarboing;
    private javax.swing.JButton bfrenarford;
    private javax.swing.JToggleButton bhonda25;
    private javax.swing.JToggleButton bhonda600;
    private javax.swing.JButton bizarvela;
    private javax.swing.JButton bmostrarbitacora;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
