package calidadpizza;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Prediccion extends javax.swing.JFrame {
    static RedNeuronal rn = new RedNeuronal();
    boolean press = false;

    public boolean isPress() {
        return press;
    }

    public void setPress(boolean press) {
        this.press = press;
    }
    
    
  
    public Prediccion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        masa = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        queso = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        champ = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        chorizo = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        carne = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        tocino = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jamon = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        pinia = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        clase = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("masa");
        jPanel10.add(jLabel2);

        jPanel8.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("queso");
        jPanel11.add(jLabel3);

        jPanel8.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("champ");
        jPanel12.add(jLabel4);

        jPanel8.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setText("chorizo");
        jPanel13.add(jLabel5);

        jPanel8.add(jPanel13);

        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setText("carne");
        jPanel18.add(jLabel6);

        jPanel8.add(jPanel18);

        jPanel20.setLayout(new java.awt.GridLayout());

        jLabel7.setText("tocino");
        jPanel20.add(jLabel7);

        jPanel8.add(jPanel20);

        jPanel21.setLayout(new java.awt.GridLayout());

        jLabel8.setText("jamon");
        jPanel21.add(jLabel8);

        jPanel8.add(jPanel21);

        jPanel22.setLayout(new java.awt.GridLayout());

        jLabel9.setText("piña");
        jPanel22.add(jLabel9);

        jPanel8.add(jPanel22);

        jPanel23.setLayout(new java.awt.GridLayout());

        jLabel10.setText("Calidad:");
        jPanel23.add(jLabel10);

        jPanel8.add(jPanel23);

        jPanel2.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        masa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaActionPerformed(evt);
            }
        });
        jPanel14.add(masa);

        jPanel9.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));
        jPanel15.add(queso);

        jPanel9.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        champ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champActionPerformed(evt);
            }
        });
        jPanel16.add(champ);

        jPanel9.add(jPanel16);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));
        jPanel17.add(chorizo);

        jPanel9.add(jPanel17);

        jPanel24.setLayout(new java.awt.GridLayout());

        carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneActionPerformed(evt);
            }
        });
        jPanel24.add(carne);

        jPanel9.add(jPanel24);

        jPanel25.setLayout(new java.awt.GridLayout());

        tocino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocinoActionPerformed(evt);
            }
        });
        jPanel25.add(tocino);

        jPanel9.add(jPanel25);

        jPanel26.setLayout(new java.awt.GridLayout());

        jamon.setEditable(false);
        jamon.setText("0.0");
        jamon.setToolTipText("");
        jamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamonActionPerformed(evt);
            }
        });
        jPanel26.add(jamon);

        jPanel9.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout());

        pinia.setEditable(false);
        pinia.setText("0.0");
        pinia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piniaActionPerformed(evt);
            }
        });
        jPanel27.add(pinia);

        jPanel9.add(jPanel27);

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        clase.setEditable(false);
        jPanel19.add(clase);

        jPanel9.add(jPanel19);

        jPanel2.add(jPanel9);

        jPanel1.add(jPanel2);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masaActionPerformed

    private void champActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
      
      double m = Double.parseDouble(masa.getText());
      double q = Double.parseDouble(queso.getText());
      double c = Double.parseDouble(champ.getText());
      double ch = Double.parseDouble(chorizo.getText());
      double ca = Double.parseDouble(carne.getText());
      double t = Double.parseDouble(tocino.getText());
      double j = Double.parseDouble(jamon.getText());
      double p = Double.parseDouble(pinia.getText());
      
      String file = ""
              + "@RELATION pizza\n" +
                "\n" +
                "@ATTRIBUTE tipo	{H,P4}\n" +
                "@ATTRIBUTE masa	REAL\n" +
                "@ATTRIBUTE queso	REAL\n" +
                "@ATTRIBUTE champ	REAL\n" +
                "@ATTRIBUTE chorizo	REAL\n" +
                "@ATTRIBUTE carne	REAL\n" +
                "@ATTRIBUTE tocino	REAL\n" +
                "@ATTRIBUTE jamon	REAL\n" +
                "@ATTRIBUTE pinia	REAL\n" +
                "@ATTRIBUTE class 	{great,good,bad}\n" +
                "\n" +
                "@DATA\n" +
                "P4,"+m+","+q+","+c+","+ch+","+ca+","+t+","+j+","+p+",?\n" +
                "%\n" +
                "%\n" +
                "%";
        escribirarchivo(file);
         clase.setText(resultado(rn.prediccionModelo()));
        press = true;
      }catch (Exception e){
          JOptionPane.showMessageDialog(null,"Ocurrio un error con los datos ingresados");
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carneActionPerformed

    private void tocinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tocinoActionPerformed

    private void jamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamonActionPerformed

    private void piniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piniaActionPerformed
     public String resultado(double pred) {
            String res = "";
            if (pred == 0.0) {
                res = "great";
            } else if (pred == 1.0) {
                res = "good";
            } else if (pred == 2.0) {
                res = "bad";
            } else {
                res = "Desconocido";
            }
            return res;
        }
     public void escribirarchivo(String lista) {
        try {
            String ruta = "src/datos/docPredic.arff";
            File archivo = new File(ruta);
            BufferedWriter bw;
            if(archivo.exists()) {
                bw = new BufferedWriter(new FileWriter(archivo));
                bw.write(lista);
            } else {
                bw = new BufferedWriter(new FileWriter(archivo));
                bw.write(lista);
            }
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Prediccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }
    
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prediccion().setVisible(true);    
            }
        });
    }

    public JTextField getClase() {
        return clase;
    }

    public void setClase(JTextField clase) {
        this.clase = clase;
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carne;
    private javax.swing.JTextField champ;
    private javax.swing.JTextField chorizo;
    private javax.swing.JTextField clase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jamon;
    private javax.swing.JTextField masa;
    private javax.swing.JTextField pinia;
    private javax.swing.JTextField queso;
    private javax.swing.JTextField tocino;
    // End of variables declaration//GEN-END:variables
}
