/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conectarsql;

import javax.swing.DefaultListModel;

/**
 *
 * @author PAVILLION
 */
public class Eliminar extends javax.swing.JPanel {
 ConectarSQL cs;
    /**
     * Creates new form Insertar
     */
    public Eliminar() {
        initComponents();
        cs= new ConectarSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        buscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        bmod = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELIMINAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24))); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Buscar Por:");
        jPanel5.add(jLabel1, new java.awt.GridBagConstraints());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Codigo de Cargo", "Nombre de Cargo" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel5.add(jComboBox1, new java.awt.GridBagConstraints());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jPanel4.add(buscar);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jPanel5.add(jPanel4, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.CardLayout());

        lista.setToolTipText("");
        jScrollPane2.setViewportView(lista);

        jPanel6.add(jScrollPane2, "card2");

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        bmod.setText("Modificar");
        bmod.setEnabled(false);
        bmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodActionPerformed(evt);
            }
        });
        jPanel3.add(bmod);

        jButton2.setText("Cancelar");
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bmod.setEnabled(true);
        if (buscar.getText().equals("")){
            cs.ejecutarConsulta(lista); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void bmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodActionPerformed
        Cargo c = lista.getSelectedValue();
        
        cs.eliminarRegistro(lista,c.getCodcar(),lista.getSelectedIndex());
    }//GEN-LAST:event_bmodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmod;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Cargo> lista;
    // End of variables declaration//GEN-END:variables
}
/*
"<html><b>Nombre de la Propiedad:</b> "+nombre + "<BR>" + "<b>Descripcion: </b>" + descripcion +"<BR><b>Sector: </b>"+sector+"<BR><b>Tipo de Contrato: </b>"+tipoc
*/