/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conectarsql;

/**
 *
 * @author PAVILLION
 */
public class Insertar extends javax.swing.JPanel {

    /**
     * Creates new form Insertar
     */
    public Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codcar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomcar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        suelmax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INSERTAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Codigo de Cargo:");
        jPanel2.add(jLabel1);
        jPanel2.add(codcar);

        jLabel2.setText("Nombre del Cargo");
        jPanel2.add(jLabel2);
        jPanel2.add(nomcar);

        jLabel3.setText("Sueldo Maximo");
        jPanel2.add(jLabel3);
        jPanel2.add(suelmax);

        jPanel1.add(jPanel2);

        jButton1.setText("Insertar");
        jPanel3.add(jButton1);

        jButton2.setText("Cancelar");
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codcar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomcar;
    private javax.swing.JTextField suelmax;
    // End of variables declaration//GEN-END:variables
}
