/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.HiloAltura;
import controlador.HiloDescenso;
import controlador.HiloFreno;
import controlador.HiloReloj;
import controlador.HiloVelocidad;
import controlador.LeerEscribirArchivos;
import controlador.Validar;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

import modelo.Ala;
import modelo.Avion;
import modelo.Rueda;

/**
 *
 * @author Leslie Diaz
 */
public class PanelAvion extends javax.swing.JFrame {

    Validar validar = new Validar();
    LeerEscribirArchivos leeresc = new LeerEscribirArchivos();
    int numeroTurbinas;
    double potencia, velocidadActual;
    Avion avion;
    HiloVelocidad hilov;
    HiloAltura hiloa;
    HiloDescenso hilod;

    public PanelAvion() {
        initComponents();
        setTitle("Panel de Control");
        setSize(750, 550);
        setLocationRelativeTo(null);
        iniciarTodo();
        HiloReloj hilor = new HiloReloj(txthora);
        hilor.start();

    }

    public void iniciarTodo() {
        txtintervelo.setEnabled(false);
        baumentarvelo.setEnabled(false);
        bpararveloc.setEnabled(false);
        txtinteraltu.setEnabled(false);
        baumentaraltu.setEnabled(false);
        bpararaltu.setEnabled(false);
        benecendido.setEnabled(false);
        bapagado.setEnabled(false);
        bdescenso.setEnabled(false);

        bfrenar.setEnabled(false);
        txtvelocidadactual.setText("0");
        txtalturaactual.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoencenapa = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtcapacidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtalturamax = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        txtalturamin = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        baumentarveloc = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        txtvelocidadmax = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        txtvelocidadmin = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        txtalas = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        txtpesoala = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        txtradiorueda = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        txtpresionrueda = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bsi = new javax.swing.JRadioButton();
        bno = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        bguardar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        controles = new javax.swing.JPanel();
        panelvelocidad = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        barravelocidad = new javax.swing.JProgressBar();
        jPanel8 = new javax.swing.JPanel();
        panelaumentovelo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtintervelo = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        baumentarvelo = new javax.swing.JToggleButton();
        bpararveloc = new javax.swing.JToggleButton();
        bfrenar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtvelocidadactual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelaltura = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        barraaltura = new javax.swing.JProgressBar();
        jPanel12 = new javax.swing.JPanel();
        panelaumentovelo1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtinteraltu = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        baumentaraltu = new javax.swing.JToggleButton();
        bpararaltu = new javax.swing.JToggleButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtalturaactual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelencapa = new javax.swing.JPanel();
        benecendido = new javax.swing.JToggleButton();
        bapagado = new javax.swing.JToggleButton();
        panelfrenaacelera = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        bparardescenso = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        bdescenso = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Avion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setLayout(new java.awt.GridLayout(10, 2));

        jLabel7.setText("Capacidad Maxima:");
        jPanel11.add(jLabel7);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        txtcapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcapacidadKeyTyped(evt);
            }
        });
        jPanel6.add(txtcapacidad);

        jLabel12.setText("[kg]");
        jPanel6.add(jLabel12);

        jPanel11.add(jPanel6);

        jLabel8.setText("Altura Maxima: ");
        jPanel11.add(jLabel8);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        txtalturamax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtalturamax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtalturamaxKeyTyped(evt);
            }
        });
        jPanel7.add(txtalturamax);

        jLabel22.setText("[pies]");
        jPanel7.add(jLabel22);

        jPanel11.add(jPanel7);

        jLabel10.setText("Altura Minima:");
        jPanel11.add(jLabel10);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.X_AXIS));

        txtalturamin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtalturamin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtalturaminKeyTyped(evt);
            }
        });
        jPanel16.add(txtalturamin);

        jLabel25.setText("[pies]");
        jPanel16.add(jLabel25);

        jPanel11.add(jPanel16);

        baumentarveloc.setText("Velocidad Maxima:");
        jPanel11.add(baumentarveloc);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.X_AXIS));

        txtvelocidadmax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtvelocidadmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvelocidadmaxKeyTyped(evt);
            }
        });
        jPanel17.add(txtvelocidadmax);

        jLabel26.setText("[Km/h]");
        jPanel17.add(jLabel26);

        jPanel11.add(jPanel17);

        jLabel11.setText("Velocidad Minima:");
        jPanel11.add(jLabel11);

        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.X_AXIS));

        txtvelocidadmin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtvelocidadmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvelocidadminKeyTyped(evt);
            }
        });
        jPanel18.add(txtvelocidadmin);

        jLabel27.setText("[Km/h]");
        jPanel18.add(jLabel27);

        jPanel11.add(jPanel18);

        jLabel18.setText("Longitud de las Alas: ");
        jPanel11.add(jLabel18);

        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.X_AXIS));

        txtalas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtalasKeyTyped(evt);
            }
        });
        jPanel20.add(txtalas);

        jLabel29.setText("[m]");
        jPanel20.add(jLabel29);

        jPanel11.add(jPanel20);

        jLabel23.setText("Peso del Ala: ");
        jPanel11.add(jLabel23);

        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.X_AXIS));

        txtpesoala.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtpesoala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpesoalaKeyTyped(evt);
            }
        });
        jPanel21.add(txtpesoala);

        jLabel30.setText("[kg]");
        jPanel21.add(jLabel30);

        jPanel11.add(jPanel21);

        jLabel9.setText("Radio de las Ruedas:");
        jPanel11.add(jLabel9);

        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.X_AXIS));

        txtradiorueda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtradiorueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtradioruedaKeyTyped(evt);
            }
        });
        jPanel19.add(txtradiorueda);

        jLabel13.setText("[m]");
        jPanel19.add(jLabel13);

        jPanel11.add(jPanel19);

        jLabel15.setText("Presion de las Ruedas:");
        jPanel11.add(jLabel15);

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.X_AXIS));

        txtpresionrueda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtpresionrueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpresionruedaKeyTyped(evt);
            }
        });
        jPanel22.add(txtpresionrueda);

        jLabel16.setText("[Pa]");
        jPanel22.add(jLabel16);

        jPanel11.add(jPanel22);

        jLabel19.setText("¿Turbinas en alas?");
        jPanel11.add(jLabel19);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup1.add(bsi);
        bsi.setText("SI");
        bsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsiMouseClicked(evt);
            }
        });
        jPanel3.add(bsi);

        buttonGroup1.add(bno);
        bno.setSelected(true);
        bno.setText("NO");
        bno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoActionPerformed(evt);
            }
        });
        jPanel3.add(bno);

        jPanel11.add(jPanel3);

        jPanel4.add(jPanel11);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.X_AXIS));

        bguardar.setText("Guardar");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });
        jPanel15.add(bguardar);

        bsalir.setText("Salir del Sistema");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel15.add(bsalir);

        jPanel4.add(jPanel15);

        jPanel1.add(jPanel4);

        controles.setLayout(new java.awt.GridLayout(2, 2));

        panelvelocidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control de Velocidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        panelvelocidad.setLayout(new javax.swing.BoxLayout(panelvelocidad, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        barravelocidad.setBackground(new java.awt.Color(225, 153, 0));
        barravelocidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        barravelocidad.setForeground(new java.awt.Color(0, 0, 0));
        barravelocidad.setRequestFocusEnabled(false);
        barravelocidad.setString("0[m/s]");
        barravelocidad.setStringPainted(true);
        jPanel5.add(barravelocidad);

        panelvelocidad.add(jPanel5);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        panelaumentovelo.setLayout(new javax.swing.BoxLayout(panelaumentovelo, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("Intervalo de Velocidad:");
        jLabel1.setToolTipText("Intervalo de aumento de velocidad");
        panelaumentovelo.add(jLabel1);

        txtintervelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinterveloKeyTyped(evt);
            }
        });
        panelaumentovelo.add(txtintervelo);

        jPanel8.add(panelaumentovelo);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup2.add(baumentarvelo);
        baumentarvelo.setText("Aumentar");
        baumentarvelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baumentarveloActionPerformed(evt);
            }
        });
        jPanel9.add(baumentarvelo);

        buttonGroup2.add(bpararveloc);
        bpararveloc.setSelected(true);
        bpararveloc.setText("Parar");
        bpararveloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpararvelocActionPerformed(evt);
            }
        });
        jPanel9.add(bpararveloc);

        bfrenar.setText("Frenar");
        bfrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfrenarActionPerformed(evt);
            }
        });
        jPanel9.add(bfrenar);

        jPanel8.add(jPanel9);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("Velocidad Actual: ");
        jPanel2.add(jLabel2);

        txtvelocidadactual.setEditable(false);
        jPanel2.add(txtvelocidadactual);

        jLabel5.setText("[m/s]");
        jPanel2.add(jLabel5);

        jPanel8.add(jPanel2);

        panelvelocidad.add(jPanel8);

        controles.add(panelvelocidad);

        panelaltura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control de Altura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        panelaltura.setLayout(new javax.swing.BoxLayout(panelaltura, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        barraaltura.setBackground(new java.awt.Color(153, 0, 255));
        barraaltura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        barraaltura.setForeground(new java.awt.Color(0, 0, 0));
        barraaltura.setString("0[m]");
        barraaltura.setStringPainted(true);
        jPanel10.add(barraaltura);

        panelaltura.add(jPanel10);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        panelaumentovelo1.setLayout(new javax.swing.BoxLayout(panelaumentovelo1, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setText("Intervalo de Altura:");
        jLabel3.setToolTipText("Intervalo de aumento de altura ");
        panelaumentovelo1.add(jLabel3);

        txtinteraltu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinteraltuKeyTyped(evt);
            }
        });
        panelaumentovelo1.add(txtinteraltu);

        jPanel12.add(panelaumentovelo1);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup3.add(baumentaraltu);
        baumentaraltu.setText("Aumentar");
        baumentaraltu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baumentaraltuActionPerformed(evt);
            }
        });
        jPanel13.add(baumentaraltu);

        buttonGroup3.add(bpararaltu);
        bpararaltu.setSelected(true);
        bpararaltu.setText("Parar");
        bpararaltu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpararaltuActionPerformed(evt);
            }
        });
        jPanel13.add(bpararaltu);

        jPanel12.add(jPanel13);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.X_AXIS));

        jLabel4.setText("Altura Actual: ");
        jPanel14.add(jLabel4);

        txtalturaactual.setEditable(false);
        jPanel14.add(txtalturaactual);

        jLabel6.setText("[m]");
        jPanel14.add(jLabel6);

        jPanel12.add(jPanel14);

        panelaltura.add(jPanel12);

        controles.add(panelaltura);

        panelencapa.setLayout(new java.awt.GridLayout(2, 1));

        grupoencenapa.add(benecendido);
        benecendido.setText("Encendido");
        benecendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benecendidoActionPerformed(evt);
            }
        });
        panelencapa.add(benecendido);

        grupoencenapa.add(bapagado);
        bapagado.setSelected(true);
        bapagado.setText("Apagado");
        bapagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bapagadoActionPerformed(evt);
            }
        });
        panelencapa.add(bapagado);

        controles.add(panelencapa);

        panelfrenaacelera.setLayout(new javax.swing.BoxLayout(panelfrenaacelera, javax.swing.BoxLayout.Y_AXIS));

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control de Descenso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel23.setLayout(new java.awt.GridLayout(2, 1));

        jPanel25.setLayout(new java.awt.GridLayout());

        bparardescenso.setText("PararDescenso");
        bparardescenso.setEnabled(false);
        bparardescenso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bparardescensoActionPerformed(evt);
            }
        });
        jPanel25.add(bparardescenso);

        jPanel23.add(jPanel25);

        jPanel26.setLayout(new java.awt.GridLayout(1, 1));

        bdescenso.setText("Descender");
        bdescenso.setEnabled(false);
        bdescenso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdescensoActionPerformed(evt);
            }
        });
        jPanel26.add(bdescenso);

        jPanel23.add(jPanel26);

        panelfrenaacelera.add(jPanel23);

        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.Y_AXIS));

        jPanel30.setLayout(new java.awt.GridLayout(1, 2));

        jLabel17.setText("Nivel de Gasolina:");
        jPanel30.add(jLabel17);

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Estable");
        jPanel30.add(jTextField1);

        jPanel29.add(jPanel30);

        jPanel31.setLayout(new java.awt.GridLayout(1, 2));

        jLabel20.setText("Hora: ");
        jPanel31.add(jLabel20);
        jPanel31.add(txthora);

        jPanel29.add(jPanel31);

        panelfrenaacelera.add(jPanel29);

        controles.add(panelfrenaacelera);

        jPanel1.add(controles);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        if (bapagado.isSelected()) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor apague el avion");
        }

    }//GEN-LAST:event_bsalirActionPerformed

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
        String capacidad = txtcapacidad.getText();
        String altuMax = txtalturamax.getText();
        String altuMin = txtalturamin.getText();
        String velocMax = txtvelocidadmax.getText();
        String velocMin = txtvelocidadmin.getText();
        String longAla = txtalas.getText();
        String pesoAla = txtpesoala.getText();
        String radioRueda = txtradiorueda.getText();
        String presionRueda = txtpresionrueda.getText();
        ArrayList<String> campos = new ArrayList<>();
        campos.add(capacidad);
        campos.add(altuMax);
        campos.add(altuMin);
        campos.add(velocMax);
        campos.add(velocMin);
        campos.add(longAla);
        campos.add(pesoAla);
        campos.add(radioRueda);
        campos.add(presionRueda);

        List<Integer> camposVacios = validar.camposVacios(campos);
        if (!camposVacios.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar los Campos Vacios");
            bsi.setEnabled(true);
            bno.setEnabled(true);
            bno.doClick();
            potencia = 0;
            numeroTurbinas = 0;
            for (Integer camposVacio : camposVacios) {
                if (null != camposVacio) {
                    switch (camposVacio) {
                        case 0:
                            txtcapacidad.setBackground(Color.red);
                            break;
                        case 1:
                            txtalturamax.setBackground(Color.red);
                            break;
                        case 2:
                            txtalturamin.setBackground(Color.red);
                            break;
                        case 3:
                            txtvelocidadmax.setBackground(Color.red);
                            break;
                        case 4:
                            txtvelocidadmin.setBackground(Color.red);
                            break;
                        case 5:
                            txtalas.setBackground(Color.red);
                            break;
                        case 6:
                            txtpesoala.setBackground(Color.red);
                            break;
                        case 7:
                            txtradiorueda.setBackground(Color.red);
                            break;
                        case 8:
                            txtpresionrueda.setBackground(Color.red);
                            break;
                        default:
                            break;
                    }
                }
            }
        } else {

            bguardar.setEnabled(false);
            benecendido.setEnabled(true);
            bapagado.setEnabled(true);
            bdescenso.setEnabled(false);

            bsi.setEnabled(false);
            bno.setEnabled(false);

            txtcapacidad.setEditable(false);
            txtcapacidad.setBackground(Color.WHITE);
            txtalturamax.setEditable(false);
            txtalturamax.setBackground(Color.WHITE);
            txtalturamin.setEditable(false);
            txtalturamin.setBackground(Color.WHITE);
            txtvelocidadmax.setEditable(false);
            txtvelocidadmax.setBackground(Color.WHITE);
            txtvelocidadmin.setEditable(false);
            txtvelocidadmin.setBackground(Color.WHITE);
            txtalas.setEditable(false);
            txtalas.setBackground(Color.WHITE);
            txtpesoala.setEditable(false);
            txtpesoala.setBackground(Color.WHITE);
            txtradiorueda.setBackground(Color.WHITE);
            txtradiorueda.setEditable(false);
            txtpresionrueda.setEditable(false);
            txtpresionrueda.setBackground(Color.WHITE);

            longAla = longAla.replace(",", ".");
            pesoAla = pesoAla.replace(",", ".");
            altuMax = altuMax.replace(",", ".");
            altuMin = altuMin.replace(",", ".");
            velocMax = velocMax.replace(",", ".");
            velocMin = velocMin.replace(",", ".");
            radioRueda = radioRueda.replace(",", ".");
            presionRueda = presionRueda.replace(",", ".");

            if (bsi.isSelected()) {
                Ala ala = new Ala(Double.parseDouble(pesoAla), Double.parseDouble(longAla), numeroTurbinas);
                ala.listaTurbina(potencia);
                Rueda rueda = new Rueda(Double.parseDouble(radioRueda), Double.parseDouble(presionRueda));
                avion = new Avion(Integer.parseInt(capacidad), Double.parseDouble(altuMax), Double.parseDouble(altuMin), Double.parseDouble(velocMin), Double.parseDouble(velocMax),
                        ala, rueda, false, "AE-320", "Aereo", 0, 0);
            } else {
                Ala ala1 = new Ala(Double.parseDouble(pesoAla), Double.parseDouble(longAla), 0);
                Rueda rueda1 = new Rueda(Double.parseDouble(radioRueda), Double.parseDouble(presionRueda));
                avion = new Avion(Integer.parseInt(capacidad), Double.parseDouble(altuMax), Double.parseDouble(altuMin), Double.parseDouble(velocMin), Double.parseDouble(velocMax),
                        ala1, rueda1, false, "AE-320", "Aereo", 0, 0);
            }
            leeresc.escribirarchivo(avion, "DatosAvion");

        }

    }//GEN-LAST:event_bguardarActionPerformed

    private void txtcapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcapacidadKeyTyped
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtcapacidadKeyTyped

    private void bnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnoActionPerformed

    private void bsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsiMouseClicked
        while (bsi.isEnabled() && bsi.isSelected()) {
            try {
                numeroTurbinas = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el numero de turbinas por ala"));
                if (numeroTurbinas > 2 || numeroTurbinas == 0) {
                    JOptionPane.showMessageDialog(null, "Error: Limite = 2; Minimo = 1");
                    bno.doClick();
                    numeroTurbinas = 0;
                } else {
                    try {
                        potencia = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese la potencia de las turbinas"));
                        bsi.setEnabled(false);
                        bno.setEnabled(false);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                        bno.doClick();
                        numeroTurbinas = 0;
                        potencia = 0;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                bno.doClick();
                numeroTurbinas = 0;
                potencia = 0;
            }
        }
    }//GEN-LAST:event_bsiMouseClicked

    private void txtpesoalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesoalaKeyTyped
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtpesoalaKeyTyped

    private void txtalturamaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalturamaxKeyTyped
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtalturamaxKeyTyped

    private void txtalturaminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalturaminKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtalturaminKeyTyped

    private void txtvelocidadmaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvelocidadmaxKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtvelocidadmaxKeyTyped

    private void txtvelocidadminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvelocidadminKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtvelocidadminKeyTyped

    private void txtalasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalasKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtalasKeyTyped

    private void txtradioruedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtradioruedaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtradioruedaKeyTyped

    private void txtpresionruedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpresionruedaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_COMMA) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtpresionruedaKeyTyped

    private void benecendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benecendidoActionPerformed
        txtintervelo.setEnabled(true);
        baumentarvelo.setEnabled(true);
        bpararveloc.setEnabled(false);
        txtinteraltu.setEnabled(true);
        baumentaraltu.setEnabled(true);
        bpararaltu.setEnabled(false);
        bfrenar.setEnabled(true);
        avion.prender();
        txtintervelo.setText("");
        txtinteraltu.setText("");
        
    }//GEN-LAST:event_benecendidoActionPerformed

    private void bapagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bapagadoActionPerformed
        if(avion.getVelocActual()==0 && avion.getAltuActual()==0){
                txtintervelo.setEnabled(false);
        baumentarvelo.setEnabled(false);
        bpararveloc.setEnabled(false);
        txtinteraltu.setEnabled(false);
        baumentaraltu.setEnabled(false);
        bpararaltu.setEnabled(false);
        bfrenar.setEnabled(false);
        
        txtalturaactual.setText("0");
        txtvelocidadactual.setText("0");
        barravelocidad.setValue(0);
        barraaltura.setValue(0);
        avion.apagar();
      } else{
            JOptionPane.showMessageDialog(null,"Por favor revise los parametros antes de apagar","Error al apagar",JOptionPane.ERROR_MESSAGE);
            benecendido.isSelected();
        }   
    }//GEN-LAST:event_bapagadoActionPerformed

    private void txtinterveloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinterveloKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtinterveloKeyTyped

    private void txtinteraltuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinteraltuKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep(); // sonido de advertencia
            evt.consume();
        }
    }//GEN-LAST:event_txtinteraltuKeyTyped

    private void baumentarveloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baumentarveloActionPerformed
        bpararveloc.setEnabled(true);
        String intervelo = txtintervelo.getText();
        ArrayList<String> campos = new ArrayList<>();
        campos.add(intervelo);
        List<Integer> camposVacios = validar.camposVacios(campos);
        if (!camposVacios.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar los Campos Vacios");
            bpararveloc.doClick();
            for (Integer camposVacio : camposVacios) {
                if (null != camposVacio) {
                    switch (camposVacio) {
                        case 0:
                            txtintervelo.setBackground(Color.red);
                            break;
                        default:
                            break;
                    }
                }
            }
        } else {
            hilov = new HiloVelocidad(barravelocidad, txtvelocidadactual, intervelo, avion, (int) avion.getVelocActual());
            hilov.start();
            txtintervelo.setEditable(false);
            if (hilov.isEstado() == true) {
                baumentarvelo.setEnabled(false);

            } else {
                baumentarvelo.setEnabled(true);
            }
           

        }
    }//GEN-LAST:event_baumentarveloActionPerformed

    private void bpararvelocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpararvelocActionPerformed
        if (!txtintervelo.getText().equals("")) {
            baumentarvelo.setEnabled(true);
            hilov.setEstado(false);
        }
    }//GEN-LAST:event_bpararvelocActionPerformed

    private void bfrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfrenarActionPerformed
        if (avion.getVelocActual() < avion.getVelocidadMax() && avion.getAltuActual()<=avion.getAlturaMin()) {
            bfrenar.setEnabled(false);
            HiloFreno hilo = new HiloFreno(avion, txtvelocidadactual, txtintervelo.getText());
            hilo.start();
        }

    }//GEN-LAST:event_bfrenarActionPerformed

    private void baumentaraltuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baumentaraltuActionPerformed
        if (avion.getVelocActual() >= avion.getVelocidadMin()) {

            bpararaltu.setEnabled(true);
            String interaltu = txtinteraltu.getText();
            ArrayList<String> campos = new ArrayList<>();
            campos.add(interaltu);
            List<Integer> camposVacios = validar.camposVacios(campos);
            if (!camposVacios.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Completar los Campos Vacios");
                bpararaltu.doClick();
                for (Integer camposVacio : camposVacios) {
                    if (null != camposVacio) {
                        switch (camposVacio) {
                            case 0:
                                txtinteraltu.setBackground(Color.red);
                                break;
                            default:
                                break;
                        }
                    }
                }
            } else {
                hiloa = new HiloAltura(barraaltura, txtalturaactual, interaltu, avion, (int) avion.getAltuActual());
                hiloa.start();
                txtinteraltu.setEditable(false);
                if (hiloa.isEstado() == true) {
                    baumentaraltu.setEnabled(false);

                } else {
                    baumentaraltu.setEnabled(true);
                }

                if (avion.getAltuActual() <= avion.getAlturaMax() && avion.getAltuActual() > 0) {
                    bdescenso.setEnabled(true);
                    
                }

            }
        }
    }//GEN-LAST:event_baumentaraltuActionPerformed

    private void bpararaltuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpararaltuActionPerformed
        // TODO add your handling code here:
        if (!txtinteraltu.getText().equals("")) {
            baumentaraltu.setEnabled(true);
            hiloa.setEstado(false);
        }
    }//GEN-LAST:event_bpararaltuActionPerformed

    private void bdescensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdescensoActionPerformed
            bdescenso.setEnabled(false);
            bparardescenso.setEnabled(true);
            hilod = new HiloDescenso(avion, txtalturaactual,txtinteraltu.getText());
            hilod.start();
            if(avion.velocActual<=0){
                bdescenso.setEnabled(false);
            }
   
    }//GEN-LAST:event_bdescensoActionPerformed

    private void bparardescensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bparardescensoActionPerformed
       if (!txtinteraltu.getText().equals("")) {
            bdescenso.setEnabled(true);
            hilod.setEstado(false);
        }
    }//GEN-LAST:event_bparardescensoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAvion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bapagado;
    private javax.swing.JProgressBar barraaltura;
    private javax.swing.JProgressBar barravelocidad;
    private javax.swing.JToggleButton baumentaraltu;
    private javax.swing.JToggleButton baumentarvelo;
    private javax.swing.JLabel baumentarveloc;
    private javax.swing.JButton bdescenso;
    private javax.swing.JToggleButton benecendido;
    private javax.swing.JButton bfrenar;
    private javax.swing.JButton bguardar;
    private javax.swing.JRadioButton bno;
    private javax.swing.JToggleButton bpararaltu;
    private javax.swing.JButton bparardescenso;
    private javax.swing.JToggleButton bpararveloc;
    private javax.swing.JButton bsalir;
    private javax.swing.JRadioButton bsi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel controles;
    private javax.swing.ButtonGroup grupoencenapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelaltura;
    private javax.swing.JPanel panelaumentovelo;
    private javax.swing.JPanel panelaumentovelo1;
    private javax.swing.JPanel panelencapa;
    private javax.swing.JPanel panelfrenaacelera;
    private javax.swing.JPanel panelvelocidad;
    private javax.swing.JFormattedTextField txtalas;
    private javax.swing.JTextField txtalturaactual;
    private javax.swing.JFormattedTextField txtalturamax;
    private javax.swing.JFormattedTextField txtalturamin;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JLabel txthora;
    private javax.swing.JTextField txtinteraltu;
    private javax.swing.JTextField txtintervelo;
    private javax.swing.JFormattedTextField txtpesoala;
    private javax.swing.JFormattedTextField txtpresionrueda;
    private javax.swing.JFormattedTextField txtradiorueda;
    private javax.swing.JTextField txtvelocidadactual;
    private javax.swing.JFormattedTextField txtvelocidadmax;
    private javax.swing.JFormattedTextField txtvelocidadmin;
    // End of variables declaration//GEN-END:variables
}
