/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Imagen;
import controlador.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Leslie Diaz
 */
public class MostrarCasa extends javax.swing.JFrame {

    AuxiliarTipoPropiedad cdt = new AuxiliarTipoPropiedad();
    Conexion cnx = new Conexion();
    PropiedadBD pbd = new PropiedadBD(cnx);

    /**
     * Creates new form AgregarCasa
     */
    public MostrarCasa(AuxiliarPropiedad ap) {
        initComponents();
        this.setSize(800, 600);
        setAlwaysOnTop(false);
        setLocationRelativeTo(null);
        setResizable(false);  // no me deja maximizar
        cdt= pbd.informacionPropiedad(ap);
        if (cdt.getNumeropisos()==0 && cdt.getPiso()==0){
            lbltipop.setText(cdt.getTipop());
            lblpiso.setText("");
            lblnump.setText("");
            lblnumban.setText("");
            lblnumhab.setText("");
        } else if (cdt.getNumeropisos()==0){
            lbltipop.setText(cdt.getTipop());
            lblpiso.setText(cdt.getPiso()+"");
           lblnump.setText("");
        } else {
            lblpiso.setText(cdt.getNumeropisos()+"");
            lbltipop.setText(cdt.getTipop());
            lblpiso.setText("");
        }
        lblprecio.setText(cdt.getPrecio()+"");
        lbltipoc.setText(cdt.getTipocontrato());
        lblnombre.setText(cdt.getNombre());
        lblcalleprincipal.setText(cdt.getCalleprincipal());
        lblcalles.setText(cdt.getCallesecundaria());
        lblsector.setText(cdt.getSector());
        lblnumpropiedad.setText(cdt.getNumerocasa());
        lblextension.setText(cdt.getExtension()+"");
        lblnumhab.setText(cdt.getNumerocuartos()+"");
        lblnumban.setText(cdt.getNumerobanios()+"");
        lbldescripcion.setText(cdt.getDescripcion());
        cbpatio.setSelected(cdt.isPatio());
        cbparqueadero.setSelected(cdt.isParqueadero());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbltipop = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbltipoc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblsector = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblcalleprincipal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblcalles = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblnumpropiedad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblextension = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblnumhab = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblnumban = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblpiso = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblnump = new javax.swing.JLabel();
        cbparqueadero = new javax.swing.JCheckBox();
        cbpatio = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnsiguiente = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 102)), "Informacion Casa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 18))); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(15, 2));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Tipo de Propiedad: ");
        jPanel2.add(jLabel7);
        jPanel2.add(lbltipop);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Condicion de la Propiedad: ");
        jPanel2.add(jLabel2);
        jPanel2.add(lbltipoc);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Nombre de la Propiedad");
        jPanel2.add(jLabel3);
        jPanel2.add(lblnombre);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Sector: ");
        jPanel2.add(jLabel4);
        jPanel2.add(lblsector);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Calle Principal:");
        jPanel2.add(jLabel5);
        jPanel2.add(lblcalleprincipal);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Calle Secundaria: ");
        jPanel2.add(jLabel6);
        jPanel2.add(lblcalles);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("Numero de Propiedad: ");
        jPanel2.add(jLabel8);
        jPanel2.add(lblnumpropiedad);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Extension:");
        jPanel2.add(jLabel9);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));
        jPanel7.add(lblextension);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel14.setText(" metros cuadrados");
        jPanel7.add(jLabel14);

        jPanel2.add(jPanel7);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Numero de Habitaciones: ");
        jPanel2.add(jLabel10);
        jPanel2.add(lblnumhab);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setText("Numero de Baños:");
        jPanel2.add(jLabel13);
        jPanel2.add(lblnumban);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setText("Precio: ");
        jPanel2.add(jLabel11);
        jPanel2.add(lblprecio);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setText("Piso: ");
        jPanel2.add(jLabel15);
        jPanel2.add(lblpiso);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel16.setText("Numero de Pisos:");
        jPanel2.add(jLabel16);
        jPanel2.add(lblnump);

        cbparqueadero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbparqueadero.setText("Parqueadero");
        cbparqueadero.setEnabled(false);
        jPanel2.add(cbparqueadero);

        cbpatio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbpatio.setText("Patio");
        cbpatio.setEnabled(false);
        jPanel2.add(cbpatio);

        jPanel1.add(jPanel2);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setText("Descripcion: ");
        jPanel8.add(jLabel12);
        jPanel8.add(lbldescripcion);

        jPanel1.add(jPanel8);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        btnsiguiente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visto.png"))); // NOI18N
        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnsiguiente);

        btncancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        dispose();
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarCasa().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JCheckBox cbparqueadero;
    private javax.swing.JCheckBox cbpatio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblcalleprincipal;
    private javax.swing.JLabel lblcalles;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblextension;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumban;
    private javax.swing.JLabel lblnumhab;
    private javax.swing.JLabel lblnump;
    private javax.swing.JLabel lblnumpropiedad;
    private javax.swing.JLabel lblpiso;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblsector;
    private javax.swing.JLabel lbltipoc;
    private javax.swing.JLabel lbltipop;
    // End of variables declaration//GEN-END:variables
}
