/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USRKAP
 */
public class Formulario extends javax.swing.JFrame {

    String auxNumeros = "";
    double resultado = 0.0;
    String operadorAux = "";

    public Formulario() {
        initComponents();
        
        setSize(500, 300);
        setLocationRelativeTo(null); //centrar la ventana
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtresultado = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        hexabutton = new javax.swing.JRadioButton();
        octalbutton = new javax.swing.JRadioButton();
        binariobutton = new javax.swing.JRadioButton();
        decimalbutton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bA = new javax.swing.JButton();
        bB = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bD = new javax.swing.JButton();
        bE = new javax.swing.JButton();
        bF = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        bCE = new javax.swing.JButton();
        bSuma = new javax.swing.JButton();
        bResta = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bMultiplicar = new javax.swing.JButton();
        bDividir = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bPunto = new javax.swing.JButton();
        bIguall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout());

        txtresultado.setEditable(false);
        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtresultado);

        jPanel1.add(jPanel2);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        buttonGroup1.add(hexabutton);
        hexabutton.setText("HEXADECIMAL");
        hexabutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hexabuttonMouseClicked(evt);
            }
        });
        jPanel6.add(hexabutton);

        buttonGroup1.add(octalbutton);
        octalbutton.setText("OCTAL");
        octalbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                octalbuttonMouseClicked(evt);
            }
        });
        jPanel6.add(octalbutton);

        buttonGroup1.add(binariobutton);
        binariobutton.setText("BINARIO");
        binariobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binariobuttonMouseClicked(evt);
            }
        });
        jPanel6.add(binariobutton);

        buttonGroup1.add(decimalbutton);
        decimalbutton.setSelected(true);
        decimalbutton.setText("DECIMAL");
        decimalbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decimalbuttonMouseClicked(evt);
            }
        });
        jPanel6.add(decimalbutton);

        jPanel1.add(jPanel6);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setLayout(new java.awt.GridLayout(3, 2));

        bA.setText("A");
        bA.setEnabled(false);
        bA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAActionPerformed(evt);
            }
        });
        jPanel4.add(bA);

        bB.setText("B");
        bB.setEnabled(false);
        bB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBActionPerformed(evt);
            }
        });
        jPanel4.add(bB);

        bC.setText("C");
        bC.setEnabled(false);
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });
        jPanel4.add(bC);

        bD.setText("D");
        bD.setEnabled(false);
        bD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDActionPerformed(evt);
            }
        });
        jPanel4.add(bD);

        bE.setText("E");
        bE.setEnabled(false);
        bE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEActionPerformed(evt);
            }
        });
        jPanel4.add(bE);

        bF.setText("F");
        bF.setEnabled(false);
        bF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFActionPerformed(evt);
            }
        });
        jPanel4.add(bF);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setLayout(new java.awt.GridLayout(3, 3));

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel7.add(b1);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel7.add(b2);

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel7.add(b3);

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel7.add(b4);

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel7.add(b5);

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel7.add(b6);

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel7.add(b7);

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel7.add(b8);

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel7.add(b9);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(3, 3));

        bCE.setText("CE");
        bCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCEActionPerformed(evt);
            }
        });
        jPanel8.add(bCE);

        bSuma.setText("+");
        bSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSumaActionPerformed(evt);
            }
        });
        jPanel8.add(bSuma);

        bResta.setText("-");
        bResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRestaActionPerformed(evt);
            }
        });
        jPanel8.add(bResta);

        bBorrar.setText("<-");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        jPanel8.add(bBorrar);

        bMultiplicar.setText("*");
        bMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiplicarActionPerformed(evt);
            }
        });
        jPanel8.add(bMultiplicar);

        bDividir.setText("/");
        bDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDividirActionPerformed(evt);
            }
        });
        jPanel8.add(bDividir);

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel8.add(b0);

        bPunto.setText(".");
        bPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuntoActionPerformed(evt);
            }
        });
        jPanel8.add(bPunto);

        bIguall.setText("=");
        bIguall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIguallActionPerformed(evt);
            }
        });
        jPanel8.add(bIguall);

        jPanel5.add(jPanel8);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, "card31");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        txtresultado.setText(txtresultado.getText() + "1");
        auxNumeros = auxNumeros + "1";
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        txtresultado.setText(txtresultado.getText() + "2");
        auxNumeros = auxNumeros + "2";
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        txtresultado.setText(txtresultado.getText() + "3");
        auxNumeros = auxNumeros + "3";
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        txtresultado.setText(txtresultado.getText() + "4");
        auxNumeros = auxNumeros + "4";
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        txtresultado.setText(txtresultado.getText() + "5");
        auxNumeros = auxNumeros + "5";
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        txtresultado.setText(txtresultado.getText() + "6");
        auxNumeros = auxNumeros + "6";
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        txtresultado.setText(txtresultado.getText() + "7");
        auxNumeros = auxNumeros + "7";
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        txtresultado.setText(txtresultado.getText() + "8");
        auxNumeros = auxNumeros + "8";
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        txtresultado.setText(txtresultado.getText() + "9");
        auxNumeros = auxNumeros + "9";
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        txtresultado.setText(txtresultado.getText() + "0");
        auxNumeros = auxNumeros + "0";
    }//GEN-LAST:event_b0ActionPerformed

    private void bIguallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIguallActionPerformed
        
        operaciones("=");
    }//GEN-LAST:event_bIguallActionPerformed

    private void bSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSumaActionPerformed
        bPunto.setEnabled(true);
        if (resultado != 0 && auxNumeros.equals("")) {
            txtresultado.setText(txtresultado.getText() + "+");
            auxNumeros = String.valueOf(resultado);
            System.out.println(resultado);
            operaciones("+");
//            System.out.println(auxNumeros);

        } else {
            txtresultado.setText(txtresultado.getText() + "+");
            operaciones("+");
        }
        txtresultado.setText("");
    }//GEN-LAST:event_bSumaActionPerformed

    private void bRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRestaActionPerformed
        bPunto.setEnabled(true);
        if (resultado != 0 && auxNumeros.equals("")) {
            txtresultado.setText(txtresultado.getText() + "-");
            auxNumeros = String.valueOf(resultado);
            operaciones("-");

        } else {
            txtresultado.setText(txtresultado.getText() + "-");
            operaciones("-");
        }
        txtresultado.setText("");;
    }//GEN-LAST:event_bRestaActionPerformed

    private void bMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiplicarActionPerformed
bPunto.setEnabled(true);
        if (resultado != 0 && auxNumeros.equals("")) {
            txtresultado.setText(txtresultado.getText() + "*");
            auxNumeros = String.valueOf(resultado);
            operaciones("*");

        } else {
            txtresultado.setText(txtresultado.getText() + "*");
            operaciones("*");
        }
        txtresultado.setText("");
    }//GEN-LAST:event_bMultiplicarActionPerformed

    private void bDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDividirActionPerformed
        bPunto.setEnabled(true);
        if (resultado != 0 && auxNumeros.equals("")) {
            txtresultado.setText(txtresultado.getText() + "/");
            auxNumeros = String.valueOf(resultado);
            operaciones("/");

        } else {
            txtresultado.setText(txtresultado.getText() + "/");
            operaciones("/");
        }
        txtresultado.setText("");
    }//GEN-LAST:event_bDividirActionPerformed

    private void bCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCEActionPerformed
        bPunto.setEnabled(true);
        txtresultado.setText("");
        resultado = 0;
        operadorAux = "";
        auxNumeros = "";
    }//GEN-LAST:event_bCEActionPerformed

    private void bPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuntoActionPerformed
        String haycadena;
        bPunto.setEnabled(false);
        haycadena = txtresultado.getText();
        if (haycadena.length()== 0) {
            txtresultado.setText("0.");
            auxNumeros = txtresultado.getText();
        } else {              
            txtresultado.setText(txtresultado.getText() + ".");
            auxNumeros = txtresultado.getText();
        }

    }//GEN-LAST:event_bPuntoActionPerformed

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed

    }//GEN-LAST:event_txtresultadoActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        String cadenanumeros;
        cadenanumeros = txtresultado.getText();
        if (cadenanumeros.length() > 0) {
            cadenanumeros = cadenanumeros.substring(0, cadenanumeros.length() - 1);
            txtresultado.setText(cadenanumeros);
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEActionPerformed
        txtresultado.setText(txtresultado.getText() + "E");
        auxNumeros = auxNumeros + "E";
    }//GEN-LAST:event_bEActionPerformed

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
        txtresultado.setText(txtresultado.getText() + "A");
        auxNumeros = auxNumeros + "A";
    }//GEN-LAST:event_bAActionPerformed

    private void bBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBActionPerformed
        txtresultado.setText(txtresultado.getText() + "B");
        auxNumeros = auxNumeros + "B";
    }//GEN-LAST:event_bBActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        txtresultado.setText(txtresultado.getText() + "C");
        auxNumeros = auxNumeros + "C";
    }//GEN-LAST:event_bCActionPerformed

    private void bDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDActionPerformed
        txtresultado.setText(txtresultado.getText() + "D");
        auxNumeros = auxNumeros + "D";
    }//GEN-LAST:event_bDActionPerformed

    private void bFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFActionPerformed
         txtresultado.setText(txtresultado.getText() + "F");
        auxNumeros = auxNumeros + "F";
    }//GEN-LAST:event_bFActionPerformed

    private void binariobuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binariobuttonMouseClicked
        txtresultado.setText("");
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
        
    }//GEN-LAST:event_binariobuttonMouseClicked

    private void decimalbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalbuttonMouseClicked
        txtresultado.setText("");
        bPunto.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
    }//GEN-LAST:event_decimalbuttonMouseClicked

    private void octalbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_octalbuttonMouseClicked
        txtresultado.setText("");
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(false);
        b9.setEnabled(false);
        
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
    }//GEN-LAST:event_octalbuttonMouseClicked

    private void hexabuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hexabuttonMouseClicked
        txtresultado.setText("");
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        
        bA.setEnabled(true);
        bB.setEnabled(true);
        bC.setEnabled(true);
        bD.setEnabled(true);
        bE.setEnabled(true);
        bF.setEnabled(true);
    }//GEN-LAST:event_hexabuttonMouseClicked

//    public static boolean haypunto(String haycadena) {
//        boolean res = false;
//        for (int i = 0; i < haycadena.length(); i++) {
//            if (haycadena.substring(i, i + 1).equals(".")) { //corresponde al contenido entre los valores el índice inicial inclusivo y índice final, exclusivo.
//                res = true;
//                break;
//            }
//        }
//        return res;
//    }

    public void operaciones(String operador) {

        switch (operador) {
            case ("+"):
                if (operadorAux.equals("")) {
                    resultado = Double.parseDouble(auxNumeros);
                    
                } else {
                    resultado = resultado + Double.parseDouble(auxNumeros);
                    
                }

                auxNumeros = "";
                operadorAux = operador;

                break;
            case ("-"):
                if (operadorAux.equals("")) {
                    resultado = Double.parseDouble(auxNumeros);
                } else {
                    resultado = resultado - Double.parseDouble(auxNumeros);
                }
                auxNumeros = "";
                operadorAux = operador;
                break;
            case ("*"):
                if (operadorAux.equals("")) {
                    resultado = Double.parseDouble(auxNumeros);
                } else {
                    resultado = resultado * Double.parseDouble(auxNumeros);
                }
                auxNumeros = "";
                operadorAux = operador;
                break;
            case ("/"):
                if (operadorAux.equals("")) {
                    resultado = Double.parseDouble(auxNumeros);
                } else {
                    resultado = resultado / Double.parseDouble(auxNumeros);
                }
                auxNumeros = "";
                operadorAux = operador;
                break;
            case ("="):
                if (operadorAux.equals("")) {
                    resultado = Double.parseDouble(auxNumeros)*0.001;
                    txtresultado.setText(resultado + "");
                    operadorAux = "";
                } else {
                    operaciones(operadorAux);
                    System.out.println(resultado);
                    txtresultado.setText(resultado + "");
                    operadorAux = "";
                }
                break;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bA;
    private javax.swing.JButton bB;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bC;
    private javax.swing.JButton bCE;
    private javax.swing.JButton bD;
    private javax.swing.JButton bDividir;
    private javax.swing.JButton bE;
    private javax.swing.JButton bF;
    private javax.swing.JButton bIguall;
    private javax.swing.JButton bMultiplicar;
    private javax.swing.JButton bPunto;
    private javax.swing.JButton bResta;
    private javax.swing.JButton bSuma;
    private javax.swing.JRadioButton binariobutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton decimalbutton;
    private javax.swing.JRadioButton hexabutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton octalbutton;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
