/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Leslie Diaz
 */
public class Registro extends javax.swing.JFrame {

    Validar validar = new Validar();
    String passEncrip, cedulaPas;
    Color color = new Color(180, 076, 067);

    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
        Date aux = new Date();
        aux.setYear(aux.getYear()-18);
        datefechana.setMaxSelectableDate(aux);
        datefechana.setDate(aux);
        datefechana.getDateEditor().setEnabled(false);
        validacionPegar();
    }

    public void validacionPegar() {
        InputMap map1 = txtapellido.getInputMap(txtapellido.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map2 = txtnombre.getInputMap(txtnombre.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map3 = formatemail.getInputMap(formatemail.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map4 = txtpass.getInputMap(txtpass.WHEN_FOCUSED);
        map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datefechana = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        formatemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        pbcontrasenia = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        btnregistrarse = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 102)), "Regístrate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 18))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Apellido:");
        jPanel1.add(jLabel1);

        txtapellido.setToolTipText("Solo Utilize Letras");
        txtapellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtapellidoFocusGained(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtapellido);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);

        txtnombre.setToolTipText("Solo Utilize Letras");
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombreFocusGained(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel5);

        datefechana.setToolTipText("");
        datefechana.setDateFormatString("dd-MM-yyyy");
        datefechana.setFocusable(false);
        jPanel1.add(datefechana);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Correo Electrónico:");
        jPanel1.add(jLabel6);

        formatemail.setToolTipText("ejemplo@email.com");
        formatemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatemailFocusGained(evt);
            }
        });
        formatemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formatemailKeyTyped(evt);
            }
        });
        jPanel1.add(formatemail);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Crea una Contraseña:");
        jPanel1.add(jLabel7);

        txtpass.setToolTipText("minimo 8 caracteres");
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });
        jPanel1.add(txtpass);
        jPanel1.add(jPanel4);

        pbcontrasenia.setStringPainted(true);
        jPanel1.add(pbcontrasenia);

        jPanel5.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 34, 0));

        btnregistrarse.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnregistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visto.png"))); // NOI18N
        btnregistrarse.setText("Registrarse");
        btnregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarseActionPerformed(evt);
            }
        });
        jPanel2.add(btnregistrarse);

        btncancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar);

        jPanel5.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel5, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarseActionPerformed
        
        int aux = 0;

        String apellido = txtapellido.getText();
        String nombre = txtnombre.getText();
        String email = formatemail.getText();
        String pass = txtpass.getText();
        String fechanacimiento = "";
        try {
            Date fecha = datefechana.getDateEditor().getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            fechanacimiento = sdf.format(fecha);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.INFORMATION_MESSAGE);
            
        }

        ArrayList<String> campos = new ArrayList<>();
        campos.add(apellido);
        campos.add(nombre);
        campos.add(email);
        campos.add(pass);
        campos.add(fechanacimiento);

        List<Integer> camposVacios = validar.camposVacios(campos);
        if (!camposVacios.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar los Campos Vacios o Incorrectos");
            for (Integer camposVacio : camposVacios) {
                if (null != camposVacio) {
                    switch (camposVacio) {
                        case 0:
                            txtapellido.setBackground(color);
                            break;
                        case 1:
                            txtnombre.setBackground(color);
                            break;
                        case 2:
                            formatemail.setBackground(color);
                            break;
                        case 3:
                            txtpass.setBackground(color);
                            break;
                        default:
                            break;
                    }
                }
            }
        } else {
            passEncrip = validar.encriptaEnMD5(pass);
            passEncrip = validar.encriptaEnMD5(passEncrip);

            boolean estado = validar.isEmail(email);
                    if (estado == true) {
                        formatemail.setBackground(Color.white);
                        if (pass.length() <= 8) {
                            JOptionPane.showMessageDialog(null, "La contraseña debe ser mayor a 8 caracteres");
                        } else {
                            if (new controlador.UserBD(new controlador.Conexion()).comprobar(email)) {
                                aux = new controlador.UserBD(new controlador.Conexion()).agregarUsuario(new controlador.UserBD(new controlador.Conexion()).leerUsuario(nombre,apellido,email, fechanacimiento, passEncrip));
                                if (aux == -1) {
                                    JOptionPane.showMessageDialog(null, "Error en el guardado");
                                } else {
                                    JOptionPane.showMessageDialog(null, "Registrado con éxito");
                                    Ingreso i = new Ingreso();
                                    i.setVisible(true);
                                    dispose();
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "El usuario ya se encuentra registrado");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Correo electrónico incorrecto");
                        formatemail.setBackground(color);
                    }
                
            

        }
    }//GEN-LAST:event_btnregistrarseActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        new Principal(new controlador.UserBD(new controlador.Conexion()).login("", "")).setVisible(true);
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != 'ñ') && (car != 'é') && (car != 'á') && (car != 'í') && (car != 'ó') && (car != 'ú') && (car != 'Ñ') && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != 'ñ') && (car != 'é') && (car != 'á') && (car != 'í') && (car != 'ó') && (car != 'ú') && (car != 'Ñ') && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped
        HiloContrasenia contra = new HiloContrasenia(pbcontrasenia, txtpass);
        contra.setDaemon(true);
        contra.start();
    }//GEN-LAST:event_txtpassKeyTyped

    private void formatemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatemailKeyTyped
        char car = evt.getKeyChar();
        if (car == ';') {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_formatemailKeyTyped

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        txtpass.setBackground(Color.white);
    }//GEN-LAST:event_txtpassFocusGained

    private void formatemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatemailFocusGained
        formatemail.setBackground(Color.white);
    }//GEN-LAST:event_formatemailFocusGained

    private void txtnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusGained
        txtnombre.setBackground(Color.white);
    }//GEN-LAST:event_txtnombreFocusGained

    private void txtapellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidoFocusGained
        txtapellido.setBackground(Color.white);
    }//GEN-LAST:event_txtapellidoFocusGained

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnregistrarse;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser datefechana;
    private javax.swing.JTextField formatemail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar pbcontrasenia;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
