/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Leslie Diaz
 */
public class Registro extends javax.swing.JFrame {

    Validar validar = new Validar();
    String passEncrip,cedulaPas;
    Color color = new Color (180,076,067);
    
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtapepat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapemat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbci = new javax.swing.JRadioButton();
        rbpasa = new javax.swing.JRadioButton();
        txtdocide = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datefechana = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        formatemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 102)), "Regístrate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 18))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Apellido Paterno:");
        jPanel1.add(jLabel1);

        txtapepat.setToolTipText("Solo Utilize Letras");
        txtapepat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapepatKeyTyped(evt);
            }
        });
        jPanel1.add(txtapepat);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Apellido Materno:");
        jPanel1.add(jLabel2);

        txtapemat.setToolTipText("Solo Utilize Letras");
        txtapemat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapematKeyTyped(evt);
            }
        });
        jPanel1.add(txtapemat);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3);

        txtnombres.setToolTipText("Solo Utilize Letras");
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombres);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Documento de Identidad:");
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        buttonGroup1.add(rbci);
        rbci.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rbci.setSelected(true);
        rbci.setText("C.I.");
        jPanel3.add(rbci, new java.awt.GridBagConstraints());

        buttonGroup1.add(rbpasa);
        rbpasa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rbpasa.setText("Pasaporte");
        jPanel3.add(rbpasa, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        txtdocide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocideActionPerformed(evt);
            }
        });
        jPanel1.add(txtdocide);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel5);

        datefechana.setToolTipText("");
        jPanel1.add(datefechana);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Correo Electrónico:");
        jPanel1.add(jLabel6);

        formatemail.setToolTipText("ejemplo@email.com");
        formatemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formatemailFocusLost(evt);
            }
        });
        formatemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatemailActionPerformed(evt);
            }
        });
        jPanel1.add(formatemail);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Crea una Contraseña:");
        jPanel1.add(jLabel7);

        txtpass.setToolTipText("minimo 8 caracteres");
        jPanel1.add(txtpass);

        jPanel5.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 34, 0));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visto.png"))); // NOI18N
        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jPanel5.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel5, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdocideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocideActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String apepat = txtapepat.getText();
        String apemat = txtapemat.getText();
        String nombre = txtnombres.getText();
        String docide = txtdocide.getText();
        String email = formatemail.getText();
        String pass = txtpass.getText();
        String fechanacimiento = datefechana.getDateFormatString();
        try {
            Date fecha = datefechana.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(fechanacimiento);
            fechanacimiento = String.valueOf(sdf.format(fecha));
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.INFORMATION_MESSAGE);
//            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }

        ArrayList<String> campos = new ArrayList<>();
        campos.add(apepat);
        campos.add(apemat);
        campos.add(nombre);
        campos.add(docide);
        campos.add(email);
        campos.add(pass);

        List<Integer> camposVacios = validar.camposVacios(campos);
        if (!camposVacios.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar los Campos Vacios");
            for (Integer camposVacio : camposVacios) {
                if (null != camposVacio) {
                    switch (camposVacio) {
                        case 0:
                            txtapepat.setBackground(color);
                            break;
                        case 1:
                            txtapemat.setBackground(color);
                            break;
                        case 2:
                            txtnombres.setBackground(color);
                            break;
                        case 3:
                            txtdocide.setBackground(color);
                            break;
                        case 4:
                            formatemail.setBackground(color);
                            break;
                        case 5:
                            txtpass.setBackground(color);
                            break;
                        default:
                            break;
                    }
                }
            }
        } else {
            passEncrip = validar.encriptaEnMD5(pass);
            passEncrip = validar.encriptaEnMD5(passEncrip);

            boolean tipodoc = true;
            if (rbci.isSelected()) {
                tipodoc = true;
            } else if (rbpasa.isSelected()) {
                tipodoc = false;
            }
            if (tipodoc == true) {
                boolean existe = verificarCedula(docide);
                if (existe == true) {
                    cedulaPas = docide;
                    txtdocide.setBackground(Color.white);
                } else {
                    mensaje();
                    txtdocide.setBackground(color);
                }
            } else {
                cedulaPas = docide;
            }
           boolean estado = validar.isEmail(email);
           if(estado==true){
               formatemail.setBackground(Color.white);
           }else{
             mensaje(); 
             formatemail.setBackground(color);
                }
           
           if (pass.length()<=8){
               JOptionPane.showMessageDialog(null,"La contraseña debe ser mayor a 8 caracteres");
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void mensaje (){
        JOptionPane.showMessageDialog(null,"campo /os incorrecto /os","Validacion de Campos",JOptionPane.INFORMATION_MESSAGE);
    }
    private void txtapepatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapepatKeyTyped
       char car = evt.getKeyChar();
       if ( (car<'a' || car>'z')&&(car<'A' || car>'Z')&& (car!=(char)KeyEvent.VK_BACK_SPACE) && (car!=(char)KeyEvent.VK_SPACE)){
           getToolkit().beep();
           evt.consume();
//        JOptionPane.showMessageDialog(null,"Solo Letras", "Caracteres no Válidos",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_txtapepatKeyTyped

    private void txtapematKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapematKeyTyped
       char car = evt.getKeyChar();
       if ( (car<'a' || car>'z')&&(car<'A' || car>'Z')&& (car!=(char)KeyEvent.VK_BACK_SPACE) && (car!=(char)KeyEvent.VK_SPACE)){
           getToolkit().beep();
           evt.consume();
           
       }
    }//GEN-LAST:event_txtapematKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
       char car = evt.getKeyChar();
       if ( (car<'a' || car>'z')&&(car<'A' || car>'Z')&& (car!=(char)KeyEvent.VK_BACK_SPACE) && (car!=(char)KeyEvent.VK_SPACE)){
          getToolkit().beep();
          evt.consume();
//        JOptionPane.showMessageDialog(null,"Solo Letras", "Caracteres no Válidos",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void formatemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatemailFocusLost
      
    }//GEN-LAST:event_formatemailFocusLost

    private void formatemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatemailActionPerformed

     public boolean verificarCedula(String cedula){
        int total=0,tamanoLongitudCedula=10,numeroProvincias=24,tercerDigito=6;
        int [] coeficientes = {2,1,2,1,2,1,2,1,2};
        if(cedula.matches("[0-9]*")&& cedula.length()==tamanoLongitudCedula){
            int provincia= Integer.parseInt(cedula.charAt(0) + "" + cedula.charAt(1));
            int digitoTres = Integer.parseInt(cedula.charAt(2) + "");
            
            if( provincia>0 && provincia<=numeroProvincias && digitoTres<tercerDigito){
                int digitoVerificadorRecibido = Integer.parseInt(cedula.charAt(9)+ "");
                for(int i=0;i<coeficientes.length;i++){
                    int valor = Integer.parseInt(coeficientes[i] + "") * Integer.parseInt(cedula.charAt(i)+ "");
                    total = valor>=10? total + (valor-9) : total + valor;
                }
                int digitoVerificadorObtenido = total >= 10 ? (total % 10) != 0 ? 10 - (total % 10) : (total % 10) : total;
                
                if(digitoVerificadorObtenido == digitoVerificadorRecibido){
                    return true;
                }
            }
            return false;
        }
    return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser datefechana;
    private javax.swing.JTextField formatemail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbci;
    private javax.swing.JRadioButton rbpasa;
    private javax.swing.JTextField txtapemat;
    private javax.swing.JTextField txtapepat;
    private javax.swing.JTextField txtdocide;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
